# Generated by Django 3.2.4 on 2021-07-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JunkDomainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserDomainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('birth_date', models.DateTimeField()),
                ('gender', models.IntegerField(default=1)),
            ],
        ),
    ]
