# Generated by Django 3.2.4 on 2021-07-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Src', '0002_auto_20210705_0057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserModel',
        ),
    ]
