# Generated by Django 3.2.4 on 2021-07-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src', '0003_rename_user_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('creation_data', models.DateField()),
                ('address', models.TextField()),
                ('postal_code', models.BigIntegerField()),
                ('phone_number', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
