# Generated by Django 3.2.4 on 2021-07-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src', '0006_rename_creation_data_user_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default=-1.0, max_length=50),
            preserve_default=False,
        ),
    ]
