# Generated by Django 3.2.4 on 2021-07-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Src', '0007_user_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
    ]
