# Generated by Django 3.2.4 on 2021-07-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src', '0011_auto_20210707_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(default=-1.0, max_length=50),
            preserve_default=False,
        ),
    ]
