# Generated by Django 3.2.4 on 2021-07-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src', '0012_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
