# Generated by Django 3.2.4 on 2021-07-09 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src', '0014_auto_20210707_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoppingCart_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('product_id', models.BigIntegerField()),
                ('product_name', models.CharField(max_length=40)),
                ('quantity', models.IntegerField()),
                ('isActive', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
