# Generated by Django 3.2.4 on 2021-07-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src', '0018_alter_shoppingcart_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
