# Generated by Django 3.2.4 on 2021-07-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src', '0019_auto_20210710_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='product_id',
            field=models.BigIntegerField(),
        ),
    ]
