# Generated by Django 3.2.4 on 2021-07-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src', '0023_auto_20210710_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
