# Generated by Django 3.2.4 on 2021-07-11 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Src', '0024_alter_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='id',
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='shoppingCart_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Src.user'),
        ),
    ]
