# Generated by Django 3.2.4 on 2021-07-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src', '0026_alter_shoppingcart_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
