# Generated by Django 3.2.4 on 2021-07-13 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src', '0027_alter_product_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('cart_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=40)),
                ('quantity', models.IntegerField()),
                ('order_status', models.IntegerField()),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='url_photo',
            field=models.CharField(default=-1.0, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
