# Generated by Django 3.2.4 on 2021-07-14 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Src', '0028_auto_20210713_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='quantity',
        ),
        migrations.AddField(
            model_name='carts',
            name='user_id',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to='Src.user'),
            preserve_default=False,
        ),
    ]
