# Generated by Django 3.2.4 on 2021-07-18 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Src', '0031_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Src.carts')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Src.user')),
            ],
        ),
    ]
