# Generated by Django 3.2.4 on 2021-07-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Src', '0032_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdmin',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
